package com.example.ui.theme

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Navigation
    val navHome: String,
    val navTasks: String,
    val navHabits: String,
    val navSuccessPath: String,
    val navProjects: String,
    val navNour: String,
    val navProgress: String,
    val navSettings: String,

    // Settings Screen
    val settingsTitle: String,
    val settingsSubtitle: String,
    val profileSection: String,
    val appearanceSection: String,
    val themeModeTitle: String,
    val themeModeDesc: String,
    val darkModeLabel: String,
    val lightModeLabel: String,
    val fontSizeTitle: String,
    val fontSizeDesc: String,
    val fontSmall: String,
    val fontMedium: String,
    val fontLarge: String,
    val languageTitle: String,
    val languageDesc: String,
    val langArabic: String,
    val langEnglish: String,
    val soundSection: String,
    val soundEffectsTitle: String,
    val soundEffectsDesc: String,
    val soundEnabledLabel: String,
    val soundMutedLabel: String,
    val soundTestButton: String,
    val apiConnectionSection: String,
    val apiConnectionTitle: String,
    val apiConnectionDesc: String,
    val apiTestButton: String,
    val apiTesting: String,
    val aboutSection: String,
    val madeInEgypt: String,
    val engineerOmarCredit: String,
    val appVersion: String,
    val dataSection: String,
    val resetAccountTitle: String,
    val resetAccountDesc: String,
    val resetAccountButton: String,
    val confirmResetTitle: String,
    val confirmResetDesc: String,
    val confirmResetAction: String,
    val cancelAction: String,

    // Success Path Screen ("مسار النجاح")
    val successPathTitle: String,
    val successPathSubtitle: String,
    val addSubjectExam: String,
    val subjectNameLabel: String,
    val examTitleLabel: String,
    val targetExamDateLabel: String,
    val totalUnitsLabel: String,
    val countdownTitle: String,
    val daysRemainingFormat: String, // e.g. "باقي %d يوماً على الامتحان"
    val daysRemainingWord: String,
    val examDatePassed: String,
    val unitsProgressTitle: String,
    val dailyAchievementTitle: String,
    val stockChartTitle: String,
    val stockChartSubtitle: String,
    val calendarTitle: String,
    val calendarSubtitle: String,
    val dayDetailTitle: String,
    val achievementRate: String,
    val tasksCompletedLabel: String,
    val studyStreakLabel: String,
    val streakMaintained: String,
    val streakBroken: String,
    val saveExamAction: String,
    val deleteExamAction: String,
    val markUnitCompleted: String,
    val marketTrendRising: String,
    val marketTrendFalling: String,
    val noExamsYet: String,
    val addFirstExamPrompt: String,
    val closeAction: String
)

val ArabicStrings = AppStrings(
    navHome = "الرئيسية",
    navTasks = "المهام",
    navHabits = "العادات",
    navSuccessPath = "مسار النجاح",
    navProjects = "المشاريع",
    navNour = "نور 💜",
    navProgress = "المستوى",
    navSettings = "الإعدادات",

    settingsTitle = "الإعدادات والملف الشخصي ⚙️",
    settingsSubtitle = "تحكم كامل وتجربة مخصصة بنسبة 100%",
    profileSection = "الملف الشخصي للطالب",
    appearanceSection = "المظهر وواجهة الاستخدام",
    themeModeTitle = "الوضع الليلي والنهاري",
    themeModeDesc = "تبديل المظهر فورياً بين الليل الداكن والنهار المشرق",
    darkModeLabel = "ليلي (Obsidian)",
    lightModeLabel = "نهاري (Pure Light)",
    fontSizeTitle = "حجم الخط العام",
    fontSizeDesc = "تكبير أو تصغير نصوص التطبيق بالكامل فوراً",
    fontSmall = "صغير",
    fontMedium = "متوسط",
    fontLarge = "كبير",
    languageTitle = "لغة واجهة التطبيق",
    languageDesc = "تغيير نصوص الواجهة واتجاه الشاشة فورياً",
    langArabic = "العربية (RTL)",
    langEnglish = "English (LTR)",
    soundSection = "التصميم الصوتي والمؤثرات",
    soundEffectsTitle = "المؤثرات الصوتية التفاعلية",
    soundEffectsDesc = "أصوات دافئة عند إنجاز المهام وزيادة الـ Streak والتحفيز",
    soundEnabledLabel = "مفعّلة 🔔",
    soundMutedLabel = "صامتة 🔕",
    soundTestButton = "تجربة نغمة الإنجاز 🎵",
    apiConnectionSection = "اتصال الذكاء الاصطناعي (Gemini API)",
    apiConnectionTitle = "فحص اتصال مساعد نور",
    apiConnectionDesc = "إرسال طلب فحص حقيقي للخوادم للتحقق من سلامة مفتاح الـ API وسرعة الاستجابة",
    apiTestButton = "اختبار الاتصال بالذكاء الاصطناعي الآن 🔌",
    apiTesting = "جارٍ فحص الاتصال بالخوادم...",
    aboutSection = "عن التطبيق وفريق العمل",
    madeInEgypt = "صُنع بكل فخر للطلبة في مصر 🇪🇬",
    engineerOmarCredit = "تم التصميم والبرمجة بواسطة المهندس عمر 👨‍💻",
    appVersion = "Nour-lv1 • الإصدار 1.0.0 Premium",
    dataSection = "إدارة البيانات وتصفير الحساب",
    resetAccountTitle = "تصفير الحساب (Zero Seed Data)",
    resetAccountDesc = "مسح جميع البيانات والعودة لحساب جديد تماماً من الصفر لتجربة ولادة النور مجدداً.",
    resetAccountButton = "تصفير الحساب والعودة للبداية 🔄",
    confirmResetTitle = "تأكيد تصفير الحساب؟",
    confirmResetDesc = "سيتم مسح كل المهام والعادات والمشاريع والعودة لحساب جديد تماماً من الصفر لتجربة ولادة النور مجدداً.",
    confirmResetAction = "تأكيد ومسح الكل",
    cancelAction = "إلغاء",

    successPathTitle = "مسار النجاح 📈",
    successPathSubtitle = "عداد الامتحانات، مؤشر البورصة، وتقويم ليلة الامتحان",
    addSubjectExam = "إضافة مادة / امتحان جديد ➕",
    subjectNameLabel = "اسم المادة (مثال: فيزياء، رياضيات)",
    examTitleLabel = "عنوان الامتحان (مثال: نهاية العام، شهادة الثانوية)",
    targetExamDateLabel = "تاريخ الامتحان (اختر بالأيام القادمة)",
    totalUnitsLabel = "إجمالي الفصول أو الوحدات",
    countdownTitle = "العد التنازلي لليلة الامتحان ⏳",
    daysRemainingFormat = "باقي %d يوماً",
    daysRemainingWord = "يوماً متبقياً",
    examDatePassed = "حان موعد الامتحان!",
    unitsProgressTitle = "منهج المادة المنجز",
    dailyAchievementTitle = "نسبة الإنجاز اليومي",
    stockChartTitle = "مؤشر البورصة التراكمي (Performance Index)",
    stockChartSubtitle = "خط بياني يصعد مع التزامك وينخفض بالتكاسل — اضغط على أي نقطة لكشف تفاصيل يومك",
    calendarTitle = "تقويم العد التنازلي لليلة الامتحان 📅",
    calendarSubtitle = "كل يوم فات محدد بعلامة X بصرية تلقائياً",
    dayDetailTitle = "تفاصيل أداء اليوم 📊",
    achievementRate = "نسبة الإنجاز المحققة:",
    tasksCompletedLabel = "المهام المنجزة للمادة:",
    studyStreakLabel = "حالة عادة المذاكرة والـ Streak:",
    streakMaintained = "مستمر وبقوة 🔥",
    streakBroken = "غير مكتمل اليوم ⚠️",
    saveExamAction = "حفظ المادة في مسار النجاح ✨",
    deleteExamAction = "حذف هذه المادة",
    markUnitCompleted = "إنجاز وحدة إضافية 📘",
    marketTrendRising = "المؤشر في صعود مستمر! 🚀 أداؤك يقترب من القمة",
    marketTrendFalling = "المؤشر تراجع قليلاً.. شد حيلك وعوّض النهاردة! 💪",
    noExamsYet = "لم تُضف أي امتحانات بعد في مسار النجاح",
    addFirstExamPrompt = "أضف أول مادة لتتبع عدادها التنازلي ومؤشر أدائها اليومي خطوة بخطوة حتى ليلة الامتحان!",
    closeAction = "إغلاق"
)

val EnglishStrings = AppStrings(
    navHome = "Home",
    navTasks = "Tasks",
    navHabits = "Habits",
    navSuccessPath = "Success Path",
    navProjects = "Projects",
    navNour = "Nour 💜",
    navProgress = "Progress",
    navSettings = "Settings",

    settingsTitle = "Settings & Profile ⚙️",
    settingsSubtitle = "Complete control and 100% personalized experience",
    profileSection = "Student Profile",
    appearanceSection = "Appearance & Interface",
    themeModeTitle = "Dark & Light Mode",
    themeModeDesc = "Instant switch between obsidian dark and pure light",
    darkModeLabel = "Dark (Obsidian)",
    lightModeLabel = "Light (Pure Light)",
    fontSizeTitle = "Global Font Size",
    fontSizeDesc = "Scales text size immediately across all app screens",
    fontSmall = "Small",
    fontMedium = "Medium",
    fontLarge = "Large",
    languageTitle = "App Interface Language",
    languageDesc = "Instantly flips layout direction (RTL/LTR) & text",
    langArabic = "العربية (RTL)",
    langEnglish = "English (LTR)",
    soundSection = "Sound Design & Effects",
    soundEffectsTitle = "Interactive Sound Effects",
    soundEffectsDesc = "Warm digital chimes for tasks, streak boosts & rewards",
    soundEnabledLabel = "Enabled 🔔",
    soundMutedLabel = "Muted 🔕",
    soundTestButton = "Preview Chime 🎵",
    apiConnectionSection = "AI Connection (Gemini API)",
    apiConnectionTitle = "Nour Assistant Diagnostics",
    apiConnectionDesc = "Send a live ping to verify Gemini API key validity and model latency",
    apiTestButton = "Test AI Connection Now 🔌",
    apiTesting = "Testing connection to servers...",
    aboutSection = "About & Credits",
    madeInEgypt = "Proudly crafted for students in Egypt 🇪🇬",
    engineerOmarCredit = "Designed and developed by Eng. Omar 👨‍💻",
    appVersion = "Nour-lv1 • Version 1.0.0 Premium",
    dataSection = "Data Management & Reset",
    resetAccountTitle = "Account Reset (Zero Seed Data)",
    resetAccountDesc = "Clears all data and restores pristine zero state to experience the birth of light again.",
    resetAccountButton = "Reset Account & Start Fresh 🔄",
    confirmResetTitle = "Confirm Reset Account?",
    confirmResetDesc = "All tasks, habits, and projects will be cleared back to zero to experience the birth of Nour again.",
    confirmResetAction = "Confirm & Clear All",
    cancelAction = "Cancel",

    successPathTitle = "Success Path 📈",
    successPathSubtitle = "Independent countdown, stock index, and exam calendar",
    addSubjectExam = "Add New Subject / Exam ➕",
    subjectNameLabel = "Subject Name (e.g., Physics, Calculus)",
    examTitleLabel = "Exam Title (e.g., Final Exam, National Exam)",
    targetExamDateLabel = "Exam Date (select future days)",
    totalUnitsLabel = "Total Units / Chapters",
    countdownTitle = "Countdown to Exam Night ⏳",
    daysRemainingFormat = "%d days left",
    daysRemainingWord = "days remaining",
    examDatePassed = "Exam day is here!",
    unitsProgressTitle = "Curriculum Units Completed",
    dailyAchievementTitle = "Daily Achievement Rate",
    stockChartTitle = "Stock Market Index (Performance)",
    stockChartSubtitle = "Ascends as you achieve goals and dips when idle — tap any point to view day details",
    calendarTitle = "Exam Countdown Calendar 📅",
    calendarSubtitle = "Past days are automatically crossed with visual X marks",
    dayDetailTitle = "Day Performance Details 📊",
    achievementRate = "Achievement Rate:",
    tasksCompletedLabel = "Tasks Completed for Subject:",
    studyStreakLabel = "Study Habit Streak Status:",
    streakMaintained = "Maintained & Active 🔥",
    streakBroken = "Incomplete on this day ⚠️",
    saveExamAction = "Save Subject to Success Path ✨",
    deleteExamAction = "Delete This Subject",
    markUnitCompleted = "Complete 1 Unit 📘",
    marketTrendRising = "Index is rising! 🚀 You are reaching peak exam readiness",
    marketTrendFalling = "Index dipped slightly.. bounce back today! 💪",
    noExamsYet = "No exams added to Success Path yet",
    addFirstExamPrompt = "Add your first subject to track its countdown timer and daily performance index step-by-step!",
    closeAction = "Close"
)

val LocalAppStrings = compositionLocalOf { ArabicStrings }
